version: '2'
services:
    #mysqlload:
        #depends_on:
          #- zoo1
          #- zoo2
          #- zoo3
          #- mysql1
        #image: mysqlload
        #tty: true
        #restart: always
        #networks:
           #backend:
             #ipv4_address: 192.168.0.8
        #command: ["/bin/sh", "/var/lib/waitformysql.sh", "192.168.0.13", "mysql"]
        #environment:
            #ZOO_MY_ID: 1
            #ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    dbtransform:
        #depends_on:
          #- zoo1
          #- zoo2
          #- zoo3
          #- mysql1
        image: dbtransform
        tty: true
        #restart: always
        networks:
           backend:
             ipv4_address: 192.168.0.9
        #command: ["/bin/sh", "/var/lib/waitformysql.sh", "192.168.0.13", "mysql"]

    tpccgendb:
        #depends_on:
          #- zoo1
          #- zoo2
          #- zoo3
          #- mysqlload
        image: tpccgendb
        tty: true
        #restart: always
        #command: ["sh","/var/lib/waitformysql.sh", "192.168.0.13", "mysql"]
        networks:
           backend:
             ipv4_address: 192.168.0.10

    #replicator:
        #depends_on:
          #- zoo1
          #- zoo2
          #- zoo3
          #- mysql1
          #- tpccgendb
        #image: replicator
        #tty: true
        #restart: always
        #command: ["sh","/var/lib/waitformysql.sh", "192.168.0.13", "mysql"]
        #networks:
           #backend:
             #ipv4_address: 192.168.0.11
        #environment:
            #ZOO_MY_ID: 1
            #ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888   

    #weaql:
        #depends_on:
          #- zoo1
          #- zoo2
          #- replicator
          #- tpccgendb
        #image: weaql
        #tty: true
        #restart: always
        #command: ["sh","/var/lib/waitformysql.sh", "192.168.0.13", "mysql"]
        #networks:
           #backend:
             #ipv4_address: 192.168.0.14
        #environment:
            #ZOO_MY_ID: 1
            #ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

networks:
  backend:
    driver: bridge
    ipam: 
      config:
      - subnet:   192.168.0.0/16
        gateway:  192.168.0.254
