@ARSETTABLE @UPDATEWINS CREATE TABLE t1 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@NUMDELTAINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a)
) ENGINE=INNODB;

@ARSETTABLE @UPDATEWINS CREATE TABLE t2 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@LWWINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a),
@UPDATEWINS FOREIGN KEY (b) REFERENCES t1(a) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;

@ARSETTABLE @UPDATEWINS CREATE TABLE t3 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@NUMDELTAINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a)
) ENGINE=INNODB;

@ARSETTABLE @DELETEWINS CREATE TABLE t4 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@NUMDELTAINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a),
@UPDATEWINS FOREIGN KEY (b) REFERENCES t1(a) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB;

@ARSETTABLE @UPDATEWINS CREATE TABLE t5 (
@LWWINTEGER a int(10) unsigned NOT NULL,
@LWWINTEGER b int(10) unsigned,
@NUMDELTAINTEGER c int(10) unsigned,
@LWWINTEGER d int(10) unsigned,
@LWWSTRING e varchar(50),
PRIMARY KEY (a)
) ENGINE=INNODB;
